# Generated by Django 4.0 on 2022-05-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='items/default.png', upload_to='items/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='meals/default.png', upload_to='meals/%Y/%m/%d/'),
        ),
    ]
