# Generated by Django 4.0 on 2022-05-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mymeal_item_quantity_usermeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymeal',
            old_name='meal',
            new_name='mymeal',
        ),
    ]
