# Generated by Django 4.0 on 2022-05-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_meal_mymeal_mymeal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMeal',
        ),
    ]
